FROM tomcat:8.0.20-jre8

MAINTAINER MapCode-Foundation

ADD mapcode-rest-service-2.2.3.5.war /usr/local/tomcat/webapps/

#RUN mkdir /usr/local/tomcat/webapps/myapp

#COPY /mapcode-foundation /usr/local/tomcat/webapps
