name: mapcode-rest-service
services:
  - name: api
    github:
      repo: mapcode-foundation/mapcode-rest-service
      branch: master
      deploy_on_push: true
    dockerfile_path: Dockerfile
    run_command: java -jar mapcode-rest-service.war --port $PORT
    http_port: 8080
    instance_size_slug: basic-xxs
