/*
 * Copyright (C) 2016-2018, Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.mapcode.services;

import com.google.gson.Gson;
import com.mapcode.Alphabet;
import com.mapcode.services.dto.AlphabetsDTO;
import org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nonnull;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@SuppressWarnings("JUnitTestMethodWithNoAssertions")
public class ApiAlphabetsTest {
    private static final Logger LOG = LoggerFactory.getLogger(ApiAlphabetsTest.class);

    private static final Double TEST_LAT1 = 50.141706;
    private static final Double TEST_LON1 = 6.135864;
    private static final String TEST_LATLON1 = TEST_LAT1 + "," + TEST_LON1;

    private LocalTestServer server;

    @Before
    public void startServer() {
        server = new LocalTestServer("1.0", 8081);
        server.start();
    }

    @After
    public void stopServer() {
        server.stop();
    }

    @Test
    public void checkAlphabetsJson() {
        LOG.info("checkAlphabetsJson");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets")).
                request().
                accept(MediaType.APPLICATION_JSON_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        final String s = response.readEntity(String.class);
        Assert.assertEquals("{\"total\":28,\"alphabets\":[{\"name\":\"ROMAN\"},{\"name\":\"GREEK\"},{\"name\":\"CYRILLIC\"},{\"name\":\"HEBREW\"},{\"name\":\"DEVANAGARI\"},{\"name\":\"MALAYALAM\"},{\"name\":\"GEORGIAN\"},{\"name\":\"KATAKANA\"},{\"name\":\"THAI\"},{\"name\":\"LAO\"},{\"name\":\"ARMENIAN\"},{\"name\":\"BENGALI\"},{\"name\":\"GURMUKHI\"},{\"name\":\"TIBETAN\"},{\"name\":\"ARABIC\"},{\"name\":\"KOREAN\"},{\"name\":\"BURMESE\"},{\"name\":\"KHMER\"},{\"name\":\"SINHALESE\"},{\"name\":\"THAANA\"},{\"name\":\"CHINESE\"},{\"name\":\"TIFINAGH\"},{\"name\":\"TAMIL\"},{\"name\":\"AMHARIC\"},{\"name\":\"TELUGU\"},{\"name\":\"ODIA\"},{\"name\":\"KANNADA\"},{\"name\":\"GUJARATI\"}]}",
                s);

        final AlphabetsDTO x = new Gson().fromJson(s, AlphabetsDTO.class);
        Assert.assertNotNull(x);
        Assert.assertEquals(28, x.getTotal());
        Assert.assertEquals("ROMAN", x.getAlphabets().get(0).getName());
    }

    @Test
    public void checkAlphabetsXml() {
        LOG.info("checkAlphabetsXml");
        final String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><alphabets><total>28</total><alphabet><name>ROMAN</name></alphabet><alphabet><name>GREEK</name></alphabet><alphabet><name>CYRILLIC</name></alphabet><alphabet><name>HEBREW</name></alphabet><alphabet><name>DEVANAGARI</name></alphabet><alphabet><name>MALAYALAM</name></alphabet><alphabet><name>GEORGIAN</name></alphabet><alphabet><name>KATAKANA</name></alphabet><alphabet><name>THAI</name></alphabet><alphabet><name>LAO</name></alphabet><alphabet><name>ARMENIAN</name></alphabet><alphabet><name>BENGALI</name></alphabet><alphabet><name>GURMUKHI</name></alphabet><alphabet><name>TIBETAN</name></alphabet><alphabet><name>ARABIC</name></alphabet><alphabet><name>KOREAN</name></alphabet><alphabet><name>BURMESE</name></alphabet><alphabet><name>KHMER</name></alphabet><alphabet><name>SINHALESE</name></alphabet><alphabet><name>THAANA</name></alphabet><alphabet><name>CHINESE</name></alphabet><alphabet><name>TIFINAGH</name></alphabet><alphabet><name>TAMIL</name></alphabet><alphabet><name>AMHARIC</name></alphabet><alphabet><name>TELUGU</name></alphabet><alphabet><name>ODIA</name></alphabet><alphabet><name>KANNADA</name></alphabet><alphabet><name>GUJARATI</name></alphabet></alphabets>";
        Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets")).
                request().
                accept(MediaType.APPLICATION_XML_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals(expected,
                response.readEntity(String.class));

        response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/xml/alphabets")).
                request().
                get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals(expected,
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetsCountJson() {
        LOG.info("checkAlphabetsCountJson");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets?count=2")).
                request().
                accept(MediaType.APPLICATION_JSON_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals("{\"total\":28,\"alphabets\":[{\"name\":\"ROMAN\"},{\"name\":\"GREEK\"}]}",
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetsCountJsonError() {
        LOG.info("checkAlphabetsCountJsonError");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets?count=-2")).
                request().
                accept(MediaType.APPLICATION_JSON_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(400, response.getStatus());
    }

    @Test
    public void checkAlphabetsCountXml() {
        LOG.info("checkAlphabetsCountXml");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets?count=2")).
                request().
                accept(MediaType.APPLICATION_XML_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><alphabets><total>28</total><alphabet><name>ROMAN</name></alphabet><alphabet><name>GREEK</name></alphabet></alphabets>",
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetsCountOffsetJson() {
        LOG.info("checkAlphabetsCountOffsetJson");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets?count=1&offset=1")).
                request().
                accept(MediaType.APPLICATION_JSON_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals("{\"total\":28,\"alphabets\":[{\"name\":\"GREEK\"}]}",
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetsCountOffsetXml() {
        LOG.info("checkAlphabetsCountOffsetXml");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets?count=1&offset=1")).
                request().
                accept(MediaType.APPLICATION_XML_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><alphabets><total>28</total><alphabet><name>GREEK</name></alphabet></alphabets>",
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetsCountOffsetFromEndJson() {
        LOG.info("checkAlphabetsCountOffsetFromEndJson");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets?count=1&offset=-1")).
                request().
                accept(MediaType.APPLICATION_JSON_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals("{\"total\":28,\"alphabets\":[{\"name\":\"GUJARATI\"}]}",
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetsCountOffsetFromEndXml() {
        LOG.info("checkAlphabetsCountOffsetXml");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets?count=1&offset=-1")).
                request().
                accept(MediaType.APPLICATION_XML_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><alphabets><total>28</total><alphabet><name>GUJARATI</name></alphabet></alphabets>",
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetJson() {
        LOG.info("checkAlphabetJson");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets/greek")).
                request().
                accept(MediaType.APPLICATION_JSON_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals("{\"name\":\"GREEK\"}",
                response.readEntity(String.class));
    }

    @Test
    public void checkAlphabetJsonError() {
        LOG.info("checkAlphabetJsonError");
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets/mozart")).
                request().
                accept(MediaType.APPLICATION_JSON_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(400, response.getStatus());
    }

    @Test
    public void checkAlphabetXmlJson() {
        LOG.info("checkAlphabetXml");
        final String expectedXml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><alphabet><name>GREEK</name></alphabet>";
        final String expectedJson = "{\"name\":\"GREEK\"}";
        Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/alphabets/greek")).
                request().
                accept(MediaType.APPLICATION_XML_TYPE).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals(expectedXml,
                response.readEntity(String.class));

        response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/xml/alphabets/greek")).
                request().
                get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals(expectedXml,
                response.readEntity(String.class));

        response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/json/alphabets/greek")).
                request().
                get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        Assert.assertEquals(expectedJson,
                response.readEntity(String.class));
    }

    @Test
    public void checkAllAlphabetsJson() {
        LOG.info("checkAlphabetsJson");
        Assert.assertEquals(Alphabet.values().length, EXPECTED_ALPHABETS_JSON.length);
        int i = 0;
        for (final Alphabet alphabet : Alphabet.values()) {

            // Reset server; cannot process this many requests, apparently.
            stopServer();
            startServer();
            doCheckAlphabet(alphabet.name(), MediaType.APPLICATION_JSON_TYPE, EXPECTED_ALPHABETS_JSON[i]);
            ++i;
            LOG.debug("checkAlphabetsJson: alphabet={}", alphabet);
        }
    }

    @Test
    public void checkAllAlphabetsXml() {
        LOG.info("checkAlphabetsXml");
        Assert.assertEquals(Alphabet.values().length, EXPECTED_ALPHABETS_XML.length);
        int i = 0;
        for (final Alphabet alphabet : Alphabet.values()) {

            // Reset server; cannot process this many requests, apparently.
            stopServer();
            startServer();
            doCheckAlphabet(alphabet.name(), MediaType.APPLICATION_XML_TYPE, EXPECTED_ALPHABETS_XML[i]);
            ++i;
            LOG.debug("checkAlphabetsXml: alphabet={}", alphabet);
        }
    }

    private void doCheckAlphabet(
            @Nonnull final String alphabet,
            @Nonnull final MediaType mediaType,
            @Nonnull final String expected) {
        LOG.info("doCheckAlphabet: alphabet={}, mediaType={}", alphabet, mediaType);
        final Response response = new ResteasyClientBuilder().build().
                target(server.url("/mapcode/codes/" + TEST_LATLON1 + "?include=territory,alphabet&alphabet=" + alphabet)).
                request().
                accept(mediaType).get();
        Assert.assertNotNull(response);
        Assert.assertEquals(200, response.getStatus());
        final String s = response.readEntity(String.class);
        Assert.assertEquals(expected, s);
    }

    private final static String[] EXPECTED_ALPHABETS_JSON = {
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"JL0.KP\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"LUX\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"VJ0L6.9PNQ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"AAA\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"JL0.KP\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"LUX\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"R8RN.07Z\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"LUX\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"SQB.NR3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"BEL\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"R8RN.07Z\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"BEL\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0L46.LG9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"DEU\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"R8RN.07Z\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"FRA\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"VJ0L6.9PNQ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"AAA\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ΠΛ0.ΚΡ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"LUX\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ΦΠ0Λ6.69Ρ1Ν\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ΑΑΑ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ΠΛ0.ΚΡ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"LUX\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Ψ8ΨΝ.07Ζ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"LUX\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ΣΘ4.Ν8Ψ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"BEL\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Ψ8ΨΝ.07Ζ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"BEL\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0Λ46.ΛΓ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"DEU\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Ψ8ΨΝ.07Ζ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ΕΨΑ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ΦΠ0Λ6.69Ρ1Ν\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ΑΑΑ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ПЛ0.КР\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ЛЭХ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ЧП0Л6.9РЗФ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ААА\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ПЛ0.КР\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ЛЭХ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Я8ЯЗ.07Б\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ЛЭХ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ЦФВ.ЗЯ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ВЕЛ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Я8ЯЗ.07Б\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ВЕЛ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0Л46.ЛГ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ДЕЭ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Я8ЯЗ.07Б\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ЖЯА\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ЧП0Л6.9РЗФ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ААА\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"טך0.ים\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ךץר\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"צט0ך6.69ם1ל\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"אאא\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"טך0.ים\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ךץר\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"נ8נל.07ת\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ךץר\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"עמ4.ל8נ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"בףך\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"נ8נל.07ת\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"בףך\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ך46.ךז9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"דףץ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"נ8נל.07ת\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"הנא\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"צט0ך6.69ם1ל\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"אאא\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ठत0.णन\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"तफस\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"लठ0त6.9नधप\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"अअअ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ठत0.णन\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"तफस\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"भ8भध.07ब\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"तफस\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"मपक.धभ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"कएत\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"भ8भध.07ब\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"कएत\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0त46.तज9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"घएफ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"भ8भध.07ब\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"चभअ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"लठ0त6.9नधप\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"अअअ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ഡഥ0.തന\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ഥഉശ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ഴഡ0ഥ6.9നധമ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ഒഒഒ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ഡഥ0.തന\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ഥഉശ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ര8രധ.07ഹ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ഥഉശ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"റമക.ധര3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"കഋഥ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ര8രധ.07ഹ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"കഋഥ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ഥ46.ഥജ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ഗഋഉ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ര8രധ.07ഹ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ചരഒ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ഴഡ0ഥ6.9നധമ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ഒഒഒ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ႮႱ0.ႰႵ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ႱႨႽ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ႺႮ0Ⴑ6.9ႵႴႶ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ႠႠႠ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ႮႱ0.ႰႵ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ႱႨႽ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Ⴗ8ႷႴ.07Ⴟ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ႱႨႽ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ႸႶႡ.ႴႷ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ႡႤႱ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Ⴗ8ႷႴ.07Ⴟ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ႡႤႱ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0Ⴑ46.ႱႫ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ႦႤႨ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Ⴗ8ႷႴ.07Ⴟ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ႩႷႠ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ႺႮ0Ⴑ6.9ႵႴႶ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ႠႠႠ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"スト0.チヒ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"トエラ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"モス0ト6.9ヒヌフ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"アアア\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"スト0.チヒ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"トエラ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ヘ8ヘヌ.07ヲ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"トエラ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ホフカ.ヌヘ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"カオト\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ヘ8ヘヌ.07ヲ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"カオト\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ト46.トコ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"クオエ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ヘ8ヘヌ.07ヲ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ケヘア\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"モス0ト6.9ヒヌフ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"アアア\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ชด0.ฑธ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ดฬอ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ลช0ด6.9ธทบ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ะะะ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ชด0.ฑธ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ดฬอ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ผ8ผท.07ฯ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ดฬอ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"มบก.ทผ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"กาด\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ผ8ผท.07ฯ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"กาด\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ด46.ดจ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"คาฬ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ผ8ผท.07ฯ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"งผะ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ลช0ด6.9ธทบ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ะะะ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ຍທ0.ດຜ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ທຽຫ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ວຍ0ທ6.9ຜບພ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ະະະ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ຍທ0.ດຜ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ທຽຫ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ມ8ມບ.07ຯ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ທຽຫ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ຢພກ.ບມ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ກໃທ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ມ8ມບ.07ຯ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ກໃທ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ທ46.ທຈ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ຄໃຽ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ມ8ມບ.07ຯ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ງມະ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ວຍ0ທ6.9ຜບພ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ະະະ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ԽՀ0.ԿՇ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ՀՅՑ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ՏԽ0Հ6.9ՇՃՈ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ՖՖՖ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ԽՀ0.ԿՇ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ՀՅՑ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Պ8ՊՃ.07Փ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ՀՅՑ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ՍՈԲ.ՃՊ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ԲԵՀ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Պ8ՊՃ.07Փ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ԲԵՀ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0Հ46.ՀԹ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ԴԵՅ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"Պ8ՊՃ.07Փ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ԸՊՖ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ՏԽ0Հ6.9ՇՃՈ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ՖՖՖ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ঝড0.ঠত\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ডটয\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"বঝ0ড6.9তণথ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"জজজ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ঝড0.ঠত\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ডটয\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"দ8দণ.07হ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ডটয\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"নথঘ.ণদ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ঘমড\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"দ8দণ.07হ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ঘমড\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ড46.ডঙ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"খমট\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"দ8দণ.07হ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"গদজ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"বঝ0ড6.9তণথ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"জজজ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ਠਤ0.ਣਨ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ਤਫਸ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ਲਠ0ਤ6.9ਨਧਪ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ਅਅਅ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ਠਤ0.ਣਨ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ਤਫਸ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ਭ8ਭਧ.07ਡ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ਤਫਸ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ਮਪਕ.ਧਭ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ਕਏਤ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ਭ8ਭਧ.07ਡ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ਕਏਤ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ਤ46.ਤਜ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ਘਏਫ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ਭ8ਭਧ.07ਡ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ਚਭਅ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ਲਠ0ਤ6.9ਨਧਪ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ਅਅਅ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ཇཕ0.ཉད\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ཕའར\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ཟཇ0ཕ6.9དཏན\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"མམམ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ཇཕ0.ཉད\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ཕའར\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"པ8པཏ.07ས\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ཕའར\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"བནཀ.ཏཔ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ཀཤཕ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"པ8པཏ.07ས\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ཀཤཕ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ཕ46.ཕཅ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"གཤའ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"པ8པཏ.07ས\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ངཔམ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ཟཇ0ཕ6.9དཏན\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"མམམ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"زش0.سط\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"شقم\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"جز0ش6.69ط1ض\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ببب\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"زش0.سط\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"شقم\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ع8عض.07و\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"شقم\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"غظ4.ض8ع3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"تثش\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ع8عض.07و\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"تثش\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ش46.شذ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"خثق\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ع8عض.07و\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"دعب\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"جز0ش6.69ط1ض\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ببب\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"타0.퍠\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ᅡᅴᄏ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ᄌᄐ0ᅡ6.69ᅤ1ᅣ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ᄒᄒᄒ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"타0.퍠\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ᅡᅴᄏ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ᅧ8ᅧᅣ.07ᅮ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ᅡᅴᄏ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ᅩᅥ4.ᅣ8ᅧ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"게ᅡ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ᅧ8ᅧᅣ.07ᅮ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"게ᅡ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ᅡ46.ᅡᄇ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"데ᅴ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ᅧ8ᅧᅣ.07ᅮ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"려ᄒ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ᄌᄐ0ᅡ6.69ᅤ1ᅣ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ᄒᄒᄒ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ဇဍ0.ဌထ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ဍဖဘ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ဟဇ0ဍ6.9ထတဒ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"စစစ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ဇဍ0.ဌထ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ဍဖဘ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"သ8သတ.07လ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ဍဖဘ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"နဒက.တသ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ကဓဍ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"သ8သတ.07လ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ကဓဍ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ဍ46.ဍင9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ဂဓဖ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"သ8သတ.07လ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ဃသစ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ဟဇ0ဍ6.9ထတဒ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"စစစ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ឈឌ0.ដទ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ឌសល\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ពឈ0ឌ6.9ទណធ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ញញញ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ឈឌ0.ដទ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ឌសល\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ន8នណ.07អ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ឌសល\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"បធក.ណន3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"កចឌ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ន8នណ.07អ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"កចឌ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ឌ46.ឌង9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"គចស\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ន8នណ.07អ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ឃនញ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ពឈ0ឌ6.9ទណធ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ញញញ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ඬද0.තප\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"දඋව\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"රඬ0ද6.9පඳබ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"අඅඅ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ඬද0.තප\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"දඋව\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ම8මඳ.07හ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"දඋව\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ඹබක.ඳම3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"කඉද\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ම8මඳ.07හ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"කඉද\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ද46.දට9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ඟඉඋ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ම8මඳ.07හ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ජමඅ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"රඬ0ද6.9පඳබ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"අඅඅ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ކވ0.އދ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ވޜޒ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ސކ0ވ6.9ދފތ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ޔޔޔ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ކވ0.އދ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ވޜޒ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ލ8ލފ.07ޱ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ވޜޒ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ގތހ.ފލ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ހޗވ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ލ8ލފ.07ޱ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ހޗވ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ވ46.ވބ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ނޗޜ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ލ8ލފ.07ޱ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ރލޔ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ސކ0ވ6.9ދފތ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ޔޔޔ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ㄋㄍ0.ㄌㄕ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ㄍㄓㄨ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ㄩㄋ0ㄍ6.9ㄕㄏㄖ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ㄣㄣㄣ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ㄋㄍ0.ㄌㄕ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ㄍㄓㄨ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ㄐ8ㄐㄏ.07ㄙ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ㄍㄓㄨ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ㄑㄖㄅ.ㄏㄐ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ㄅㄔㄍ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ㄐ8ㄐㄏ.07ㄙ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ㄅㄔㄍ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ㄍ46.ㄍㄉ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ㄆㄔㄓ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ㄐ8ㄐㄏ.07ㄙ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ㄇㄐㄣ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ㄩㄋ0ㄍ6.9ㄕㄏㄖ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ㄣㄣㄣ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ⵃⵅ0.ⵄⵎ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ⵅⵢⵟ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ⵛⵃ0ⵅ6.9ⵎⵍⵕ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ⵉⵉⵉ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ⵃⵅ0.ⵄⵎ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ⵅⵢⵟ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ⵖ8ⵖⵍ.07ⵣ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ⵅⵢⵟ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ⵙⵕⴱ.ⵍⵖ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ⴱⵓⵅ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ⵖ8ⵖⵍ.07ⵣ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ⴱⵓⵅ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ⵅ46.ⵅⴽ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ⴷⵓⵢ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ⵖ8ⵖⵍ.07ⵣ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ⴼⵖⵉ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ⵛⵃ0ⵅ6.9ⵎⵍⵕ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ⵉⵉⵉ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"மர0.யழ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ரஓஏ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"உம0ர6.9ழவள\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ஙஙங\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"மர0.யழ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ரஓஏ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ற8றவ.07ஒ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ரஓஏ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"அளக.வற3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"கஆர\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ற8றவ.07ஒ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"கஆர\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ர46.ரந9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"டஆஓ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ற8றவ.07ஒ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"தறங\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"உம0ர6.9ழவள\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ஙஙங\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"የለ0.ኬፔ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ለወቶ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ሦየ0ለ6.9ፔፐቀ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ማማማ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"የለ0.ኬፔ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ለወቶ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ቄ8ቄፐ.07ዜ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ለወቶ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ሬቀበ.ፐቄ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"በሞለ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ቄ8ቄፐ.07ዜ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"በሞለ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ለ46.ለገ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ደሞወ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ቄ8ቄፐ.07ዜ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ፊቄማ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ሦየ0ለ6.9ፔፐቀ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ማማማ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ఠణ0.డద\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ణభల\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"మఠ0ణ6.9దథధ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ఞఞఞ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ఠణ0.డద\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ణభల\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"న8నథ.07వ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ణభల\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"పధక.థన3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"కఫణ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"న8నథ.07వ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"కఫణ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ణ46.ణజ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ఙఫభ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"న8నథ.07వ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"చనఞ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"మఠ0ణ6.9దథధ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ఞఞఞ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ଟଢ0.ଡଦ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ଢହର\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ମଟ0ଢ6.9ଦଥଧ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ଝଝଝ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ଟଢ0.ଡଦ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ଢହର\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ନ8ନଥ.07ସ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ଢହର\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ପଧକ.ଥନ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"କଣଢ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ନ8ନଥ.07ସ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"କଣଢ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ଢ46.ଢଚ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ଗଣହ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ନ8ନଥ.07ସ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ଘନଝ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ମଟ0ଢ6.9ଦଥଧ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ଝଝଝ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ಜಡ0.ಠದ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ಡಇರ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ಬಜ0ಡ6.9ದತಧ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ಒಒಒ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ಜಡ0.ಠದ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ಡಇರ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ನ8ನತ.07ವ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"ಡಇರ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"ಪಧಕ.ತನ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ಕಎಡ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ನ8ನತ.07ವ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ಕಎಡ\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ಡ46.ಡಚ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ಗಎಇ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ನ8ನತ.07ವ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"ಙನಒ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ಬಜ0ಡ6.9ದತಧ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ಒಒಒ\"}]}",
            "{\"local\":{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ચત0.ટર\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"તઉઝ\"},\"international\":{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ષચ0ત6.9રઠવ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ળળળ\"},\"mapcodes\":[{\"mapcode\":\"JL0.KP\",\"mapcodeInAlphabet\":\"ચત0.ટર\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"તઉઝ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ઞ8ઞઠ.07ભ\",\"territory\":\"LUX\",\"territoryInAlphabet\":\"તઉઝ\"},{\"mapcode\":\"SQB.NR3\",\"mapcodeInAlphabet\":\"મવગ.ઠઞ3\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ગઇત\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ઞ8ઞઠ.07ભ\",\"territory\":\"BEL\",\"territoryInAlphabet\":\"ગઇત\"},{\"mapcode\":\"0L46.LG9\",\"mapcodeInAlphabet\":\"0ત46.તબ9\",\"territory\":\"DEU\",\"territoryInAlphabet\":\"ડઇઉ\"},{\"mapcode\":\"R8RN.07Z\",\"mapcodeInAlphabet\":\"ઞ8ઞઠ.07ભ\",\"territory\":\"FRA\",\"territoryInAlphabet\":\"દઞળ\"},{\"mapcode\":\"VJ0L6.9PNQ\",\"mapcodeInAlphabet\":\"ષચ0ત6.9રઠવ\",\"territory\":\"AAA\",\"territoryInAlphabet\":\"ળળળ\"}]}",
    };
    private final static String[] EXPECTED_ALPHABETS_XML = {
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>JL0.KP</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>LUX</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>VJ0L6.9PNQ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>AAA</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>JL0.KP</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>LUX</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>R8RN.07Z</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>LUX</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>SQB.NR3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>BEL</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>R8RN.07Z</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>BEL</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0L46.LG9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>DEU</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>R8RN.07Z</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>FRA</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>VJ0L6.9PNQ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>AAA</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ΠΛ0.ΚΡ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>LUX</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ΦΠ0Λ6.69Ρ1Ν</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ΑΑΑ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ΠΛ0.ΚΡ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>LUX</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Ψ8ΨΝ.07Ζ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>LUX</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ΣΘ4.Ν8Ψ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>BEL</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Ψ8ΨΝ.07Ζ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>BEL</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0Λ46.ΛΓ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>DEU</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Ψ8ΨΝ.07Ζ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ΕΨΑ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ΦΠ0Λ6.69Ρ1Ν</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ΑΑΑ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ПЛ0.КР</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ЛЭХ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ЧП0Л6.9РЗФ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ААА</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ПЛ0.КР</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ЛЭХ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Я8ЯЗ.07Б</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ЛЭХ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ЦФВ.ЗЯ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ВЕЛ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Я8ЯЗ.07Б</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ВЕЛ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0Л46.ЛГ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ДЕЭ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Я8ЯЗ.07Б</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ЖЯА</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ЧП0Л6.9РЗФ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ААА</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>טך0.ים</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ךץר</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>צט0ך6.69ם1ל</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>אאא</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>טך0.ים</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ךץר</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>נ8נל.07ת</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ךץר</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>עמ4.ל8נ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>בףך</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>נ8נל.07ת</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>בףך</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ך46.ךז9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>דףץ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>נ8נל.07ת</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>הנא</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>צט0ך6.69ם1ל</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>אאא</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ठत0.णन</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>तफस</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>लठ0त6.9नधप</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>अअअ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ठत0.णन</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>तफस</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>भ8भध.07ब</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>तफस</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>मपक.धभ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>कएत</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>भ8भध.07ब</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>कएत</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0त46.तज9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>घएफ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>भ8भध.07ब</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>चभअ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>लठ0त6.9नधप</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>अअअ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ഡഥ0.തന</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ഥഉശ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ഴഡ0ഥ6.9നധമ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ഒഒഒ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ഡഥ0.തന</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ഥഉശ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ര8രധ.07ഹ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ഥഉശ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>റമക.ധര3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>കഋഥ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ര8രധ.07ഹ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>കഋഥ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ഥ46.ഥജ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ഗഋഉ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ര8രധ.07ഹ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ചരഒ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ഴഡ0ഥ6.9നധമ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ഒഒഒ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ႮႱ0.ႰႵ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ႱႨႽ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ႺႮ0Ⴑ6.9ႵႴႶ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ႠႠႠ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ႮႱ0.ႰႵ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ႱႨႽ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Ⴗ8ႷႴ.07Ⴟ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ႱႨႽ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ႸႶႡ.ႴႷ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ႡႤႱ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Ⴗ8ႷႴ.07Ⴟ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ႡႤႱ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0Ⴑ46.ႱႫ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ႦႤႨ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Ⴗ8ႷႴ.07Ⴟ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ႩႷႠ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ႺႮ0Ⴑ6.9ႵႴႶ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ႠႠႠ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>スト0.チヒ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>トエラ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>モス0ト6.9ヒヌフ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>アアア</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>スト0.チヒ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>トエラ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ヘ8ヘヌ.07ヲ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>トエラ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ホフカ.ヌヘ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>カオト</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ヘ8ヘヌ.07ヲ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>カオト</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ト46.トコ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>クオエ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ヘ8ヘヌ.07ヲ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ケヘア</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>モス0ト6.9ヒヌフ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>アアア</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ชด0.ฑธ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ดฬอ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ลช0ด6.9ธทบ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ะะะ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ชด0.ฑธ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ดฬอ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ผ8ผท.07ฯ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ดฬอ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>มบก.ทผ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>กาด</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ผ8ผท.07ฯ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>กาด</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ด46.ดจ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>คาฬ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ผ8ผท.07ฯ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>งผะ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ลช0ด6.9ธทบ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ะะะ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ຍທ0.ດຜ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ທຽຫ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ວຍ0ທ6.9ຜບພ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ະະະ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ຍທ0.ດຜ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ທຽຫ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ມ8ມບ.07ຯ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ທຽຫ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ຢພກ.ບມ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ກໃທ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ມ8ມບ.07ຯ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ກໃທ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ທ46.ທຈ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ຄໃຽ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ມ8ມບ.07ຯ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ງມະ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ວຍ0ທ6.9ຜບພ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ະະະ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ԽՀ0.ԿՇ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ՀՅՑ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ՏԽ0Հ6.9ՇՃՈ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ՖՖՖ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ԽՀ0.ԿՇ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ՀՅՑ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Պ8ՊՃ.07Փ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ՀՅՑ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ՍՈԲ.ՃՊ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ԲԵՀ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Պ8ՊՃ.07Փ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ԲԵՀ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0Հ46.ՀԹ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ԴԵՅ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>Պ8ՊՃ.07Փ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ԸՊՖ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ՏԽ0Հ6.9ՇՃՈ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ՖՖՖ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ঝড0.ঠত</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ডটয</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>বঝ0ড6.9তণথ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>জজজ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ঝড0.ঠত</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ডটয</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>দ8দণ.07হ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ডটয</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>নথঘ.ণদ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ঘমড</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>দ8দণ.07হ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ঘমড</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ড46.ডঙ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>খমট</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>দ8দণ.07হ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>গদজ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>বঝ0ড6.9তণথ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>জজজ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ਠਤ0.ਣਨ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ਤਫਸ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ਲਠ0ਤ6.9ਨਧਪ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ਅਅਅ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ਠਤ0.ਣਨ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ਤਫਸ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ਭ8ਭਧ.07ਡ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ਤਫਸ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ਮਪਕ.ਧਭ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ਕਏਤ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ਭ8ਭਧ.07ਡ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ਕਏਤ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ਤ46.ਤਜ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ਘਏਫ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ਭ8ਭਧ.07ਡ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ਚਭਅ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ਲਠ0ਤ6.9ਨਧਪ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ਅਅਅ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ཇཕ0.ཉད</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ཕའར</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ཟཇ0ཕ6.9དཏན</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>མམམ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ཇཕ0.ཉད</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ཕའར</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>པ8པཏ.07ས</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ཕའར</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>བནཀ.ཏཔ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ཀཤཕ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>པ8པཏ.07ས</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ཀཤཕ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ཕ46.ཕཅ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>གཤའ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>པ8པཏ.07ས</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ངཔམ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ཟཇ0ཕ6.9དཏན</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>མམམ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>زش0.سط</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>شقم</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>جز0ش6.69ط1ض</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ببب</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>زش0.سط</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>شقم</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ع8عض.07و</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>شقم</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>غظ4.ض8ع3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>تثش</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ع8عض.07و</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>تثش</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ش46.شذ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>خثق</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ع8عض.07و</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>دعب</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>جز0ش6.69ط1ض</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ببب</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>타0.퍠</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ᅡᅴᄏ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ᄌᄐ0ᅡ6.69ᅤ1ᅣ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ᄒᄒᄒ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>타0.퍠</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ᅡᅴᄏ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ᅧ8ᅧᅣ.07ᅮ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ᅡᅴᄏ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ᅩᅥ4.ᅣ8ᅧ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>게ᅡ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ᅧ8ᅧᅣ.07ᅮ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>게ᅡ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ᅡ46.ᅡᄇ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>데ᅴ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ᅧ8ᅧᅣ.07ᅮ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>려ᄒ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ᄌᄐ0ᅡ6.69ᅤ1ᅣ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ᄒᄒᄒ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ဇဍ0.ဌထ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ဍဖဘ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ဟဇ0ဍ6.9ထတဒ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>စစစ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ဇဍ0.ဌထ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ဍဖဘ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>သ8သတ.07လ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ဍဖဘ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>နဒက.တသ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ကဓဍ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>သ8သတ.07လ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ကဓဍ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ဍ46.ဍင9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ဂဓဖ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>သ8သတ.07လ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ဃသစ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ဟဇ0ဍ6.9ထတဒ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>စစစ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ឈឌ0.ដទ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ឌសល</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ពឈ0ឌ6.9ទណធ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ញញញ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ឈឌ0.ដទ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ឌសល</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ន8នណ.07អ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ឌសល</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>បធក.ណន3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>កចឌ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ន8នណ.07អ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>កចឌ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ឌ46.ឌង9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>គចស</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ន8នណ.07អ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ឃនញ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ពឈ0ឌ6.9ទណធ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ញញញ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ඬද0.තප</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>දඋව</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>රඬ0ද6.9පඳබ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>අඅඅ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ඬද0.තප</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>දඋව</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ම8මඳ.07හ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>දඋව</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ඹබක.ඳම3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>කඉද</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ම8මඳ.07හ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>කඉද</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ද46.දට9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ඟඉඋ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ම8මඳ.07හ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ජමඅ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>රඬ0ද6.9පඳබ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>අඅඅ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ކވ0.އދ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ވޜޒ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ސކ0ވ6.9ދފތ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ޔޔޔ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ކވ0.އދ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ވޜޒ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ލ8ލފ.07ޱ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ވޜޒ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ގތހ.ފލ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ހޗވ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ލ8ލފ.07ޱ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ހޗވ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ވ46.ވބ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ނޗޜ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ލ8ލފ.07ޱ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ރލޔ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ސކ0ވ6.9ދފތ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ޔޔޔ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ㄋㄍ0.ㄌㄕ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ㄍㄓㄨ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ㄩㄋ0ㄍ6.9ㄕㄏㄖ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ㄣㄣㄣ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ㄋㄍ0.ㄌㄕ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ㄍㄓㄨ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ㄐ8ㄐㄏ.07ㄙ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ㄍㄓㄨ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ㄑㄖㄅ.ㄏㄐ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ㄅㄔㄍ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ㄐ8ㄐㄏ.07ㄙ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ㄅㄔㄍ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ㄍ46.ㄍㄉ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ㄆㄔㄓ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ㄐ8ㄐㄏ.07ㄙ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ㄇㄐㄣ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ㄩㄋ0ㄍ6.9ㄕㄏㄖ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ㄣㄣㄣ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ⵃⵅ0.ⵄⵎ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ⵅⵢⵟ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ⵛⵃ0ⵅ6.9ⵎⵍⵕ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ⵉⵉⵉ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ⵃⵅ0.ⵄⵎ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ⵅⵢⵟ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ⵖ8ⵖⵍ.07ⵣ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ⵅⵢⵟ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ⵙⵕⴱ.ⵍⵖ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ⴱⵓⵅ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ⵖ8ⵖⵍ.07ⵣ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ⴱⵓⵅ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ⵅ46.ⵅⴽ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ⴷⵓⵢ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ⵖ8ⵖⵍ.07ⵣ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ⴼⵖⵉ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ⵛⵃ0ⵅ6.9ⵎⵍⵕ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ⵉⵉⵉ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>மர0.யழ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ரஓஏ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>உம0ர6.9ழவள</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ஙஙங</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>மர0.யழ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ரஓஏ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ற8றவ.07ஒ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ரஓஏ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>அளக.வற3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>கஆர</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ற8றவ.07ஒ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>கஆர</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ர46.ரந9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>டஆஓ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ற8றவ.07ஒ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>தறங</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>உம0ர6.9ழவள</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ஙஙங</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>የለ0.ኬፔ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ለወቶ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ሦየ0ለ6.9ፔፐቀ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ማማማ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>የለ0.ኬፔ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ለወቶ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ቄ8ቄፐ.07ዜ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ለወቶ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ሬቀበ.ፐቄ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>በሞለ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ቄ8ቄፐ.07ዜ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>በሞለ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ለ46.ለገ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ደሞወ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ቄ8ቄፐ.07ዜ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ፊቄማ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ሦየ0ለ6.9ፔፐቀ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ማማማ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ఠణ0.డద</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ణభల</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>మఠ0ణ6.9దథధ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ఞఞఞ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ఠణ0.డద</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ణభల</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>న8నథ.07వ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ణభల</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>పధక.థన3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>కఫణ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>న8నథ.07వ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>కఫణ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ణ46.ణజ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ఙఫభ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>న8నథ.07వ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>చనఞ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>మఠ0ణ6.9దథధ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ఞఞఞ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ଟଢ0.ଡଦ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ଢହର</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ମଟ0ଢ6.9ଦଥଧ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ଝଝଝ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ଟଢ0.ଡଦ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ଢହର</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ନ8ନଥ.07ସ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ଢହର</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ପଧକ.ଥନ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>କଣଢ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ନ8ନଥ.07ସ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>କଣଢ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ଢ46.ଢଚ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ଗଣହ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ନ8ନଥ.07ସ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ଘନଝ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ମଟ0ଢ6.9ଦଥଧ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ଝଝଝ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ಜಡ0.ಠದ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ಡಇರ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ಬಜ0ಡ6.9ದತಧ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ಒಒಒ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ಜಡ0.ಠದ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ಡಇರ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ನ8ನತ.07ವ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>ಡಇರ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>ಪಧಕ.ತನ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ಕಎಡ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ನ8ನತ.07ವ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ಕಎಡ</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ಡ46.ಡಚ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ಗಎಇ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ನ8ನತ.07ವ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>ಙನಒ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ಬಜ0ಡ6.9ದತಧ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ಒಒಒ</territoryInAlphabet></mapcode></mapcodes></mapcodes>",
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><mapcodes><local><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ચત0.ટર</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>તઉઝ</territoryInAlphabet></local><international><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ષચ0ત6.9રઠવ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ળળળ</territoryInAlphabet></international><mapcodes><mapcode><mapcode>JL0.KP</mapcode><mapcodeInAlphabet>ચત0.ટર</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>તઉઝ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ઞ8ઞઠ.07ભ</mapcodeInAlphabet><territory>LUX</territory><territoryInAlphabet>તઉઝ</territoryInAlphabet></mapcode><mapcode><mapcode>SQB.NR3</mapcode><mapcodeInAlphabet>મવગ.ઠઞ3</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ગઇત</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ઞ8ઞઠ.07ભ</mapcodeInAlphabet><territory>BEL</territory><territoryInAlphabet>ગઇત</territoryInAlphabet></mapcode><mapcode><mapcode>0L46.LG9</mapcode><mapcodeInAlphabet>0ત46.તબ9</mapcodeInAlphabet><territory>DEU</territory><territoryInAlphabet>ડઇઉ</territoryInAlphabet></mapcode><mapcode><mapcode>R8RN.07Z</mapcode><mapcodeInAlphabet>ઞ8ઞઠ.07ભ</mapcodeInAlphabet><territory>FRA</territory><territoryInAlphabet>દઞળ</territoryInAlphabet></mapcode><mapcode><mapcode>VJ0L6.9PNQ</mapcode><mapcodeInAlphabet>ષચ0ત6.9રઠવ</mapcodeInAlphabet><territory>AAA</territory><territoryInAlphabet>ળળળ</territoryInAlphabet></mapcode></mapcodes></mapcodes>"
    };
}
